// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	Movies           string
	Permissions      string
	SchemaMigrations string
	Tokens           string
	Users            string
	UsersPermissions string
}{
	Movies:           "movies",
	Permissions:      "permissions",
	SchemaMigrations: "schema_migrations",
	Tokens:           "tokens",
	Users:            "users",
	UsersPermissions: "users_permissions",
}
